name: Stardust

on:
  push:
    branches: [ edge ]
  pull_request:
    branches: [ edge ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
          git submodule update --init --recursive --remote
          mkdir -p build
          cd build
          cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release ..
          make
          make test
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Stardust-Celeste-Linux
          path: |
            build/libStardust-Celeste.a
            build/libSC-Entry.a
            LICENSE
            README.md

  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          git submodule update --init --recursive --remote
          cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 .
          cmake --build . --config Release
          cmake --build . --config Release --target RUN_TESTS
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Stardust-Celeste-Windows
          path: |
            Release\Stardust-Celeste.lib
            Release\SC-Entry.lib
            LICENSE
            README.md

  PSP:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Install dependencies
        run: |
          apk add bash cmake git gmp mpc1 mpfr4 make glew sdl2 binutils libc6-compat
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          git config --global --add safe.directory /__w/Stardust-Celeste/Stardust-Celeste
          git submodule update --init --recursive --remote
          mkdir -p build
          cd build
          cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake ..
          make
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Stardust-Celeste-PSP
          path: |
            build/libStardust-Celeste.a
            build/libSC-Entry.a
            LICENSE
            README.md
